---
- name: Deploy chat app to minikube
  hosts: localhost

  tasks:
    - name: Apply backend
      shell: kubectl apply -f ../kubernetes/backend.yaml

    # Uncomment and modify the following tasks as needed
    # - name: apply elasticsearch
    #   shell: kubectl apply -f ../kubernetes/elasticsearch.yaml
    #   environment:
    #     KUBECONFIG: "{{ kubeconfig }}"
    #   become: false  # No need for sudo here, depending on your setup

    # - name: apply logstash
    #   shell: kubectl apply -f ../kubernetes/logstash.yaml
    #   environment:
    #     KUBECONFIG: "{{ kubeconfig }}"
    #   become: false  # No need for sudo here, depending on your setup

    # - name: apply kibana
    #   shell: kubectl apply -f ../kubernetes/kibana.yaml
    #   environment:
    #     KUBECONFIG: "{{ kubeconfig }}"
    #   become: false  # No need for sudo here, depending on your setup

    # - name: apply filebeat
    #   shell: kubectl apply -f ../kubernetes/filebeat.yaml
    #   environment:
    #     KUBECONFIG: "{{ kubeconfig }}"
    #   become: false  # No need for sudo here, depending on your setup
