---
- name: Deploy chat app to minikube
  hosts: all
  tasks:
    - name: apply backend
      shell: kubectl apply -f ../kubernates/backend.yaml

    - name: apply frontend
      shell: kubectl apply -f ./kubernates/frontend.yaml

    # - name: apply elasticsearch
    #   shell: kubectl apply -f ../kubernetes/elasticsearch.yaml

    # - name: apply logstash
    #   shell: kubectl apply -f ../kubernetes/logstash.yaml

    # - name: apply kibana
    #   shell: kubectl apply -f ../kubernetes/kibana.yaml

    # - name: apply filebeat
    #   shell: kubectl apply -f ../kubernetes/filebeat.yaml