---
- name: Deploy chat app to minikube
  hosts: local
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no  # Skip gathering facts to speed up the process

  vars:
    ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"

  tasks:
    - name: Deploy frontend
      shell: KUBECONFIG=/home/sankalp/.kube/config kubectl apply -f ../kubernetes/frontend.yaml --validate=false
      register: frontend_deploy_result
      ignore_errors: yes

    - name: Deploy frontend
      shell: KUBECONFIG=/home/sankalp/.kube/config kubectl apply -f ../kubernetes/backend.yaml --validate=false
      register: backend_deploy_result
    - name: Deploy frontend

      shell: KUBECONFIG=/home/sankalp/.kube/config kubectl apply -f ../kubernetes/logstash.yaml --validate=false
      register: backend_deploy_result
