---
# Frontend Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  annotations:
    redeployTimestamp: "2024-05-24T14:30:00Z" # Update this value to force redeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: sankalp137rai/react-app:frontend1
        ports:
        - containerPort: 3000
---
# Frontend Services
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30347